apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: app-b
  name: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app-b
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: app-b
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: xdb
            - name: MYSQL_HOST
              value: estudiante_xdb_1
            - name: MYSQL_PASSWORD
              value: "123456"
            - name: MYSQL_USER
              value: root
          image: app-b
          name: app_b
          ports:
            - containerPort: 8502
            - containerPort: 8002
          resources:
            limits:
              cpu: "1"
              memory: "838860800"
            requests:
              memory: "838860800"
          volumeMounts:
            - mountPath: /APIB
              name: app-b-claim0
            - mountPath: /M_1/data
              name: app-b-claim1
      restartPolicy: Always
      volumes:
        - name: app-b-claim0
          persistentVolumeClaim:
            claimName: app-b-claim0
        - name: app-b-claim1
          persistentVolumeClaim:
            claimName: app-b-claim1
status: {}
