apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-x
  name: db-x
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-x
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db-x
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: xdb
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          image: mysql:latest
          name: db_x
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db-x-claim0
      hostname: estudiante_xdb_1
      restartPolicy: Always
      volumes:
        - name: db-x-claim0
          persistentVolumeClaim:
            claimName: db-x-claim0
status: {}
