apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: db-z
  name: db_z
spec:
  ports:
    - name: "3307"
      port: 3307
      targetPort: 3307
  selector:
    io.kompose.service: db-z
status:
  loadBalancer: {}
